#!/bin/bash

cd $HOME

sleep 5
tigervncserver -depth 24 -localhost yes -SecurityTypes none :1 -- /usr/bin/fluxbox &

(cd /opt/novnc/; ./utils/novnc_proxy --vnc localhost:5901 &)

mkdir -p $HOME/.vscode-server/data/Machine/ $HOME/.vscode

cat << EOF > $HOME/.vscode-server/data/Machine/settings.json
{
  "remote.autoForwardPorts": true,
  "remote.portsAttributes": {
    "6080": {
      "label": "VNC",
      "onAutoForward": "notify"
    }
  }
}
EOF

cp $HOME/.vscode-server/data/Machine/settings.json $HOME/.vscode/settings.json

bash init && code tunnel --accept-server-license-terms --disable-telemetry --name ${MACHINE_NAME} \
    --install-extension ms-vscode-remote.remote-containers \
    --install-extension GitHub.copilot \
    --install-extension GitHub.copilot-chat \
    --install-extension anthropic.claude-code \
    --install-extension ms-python.python \
    --install-extension ms-toolsai.jupyter \
    --install-extension ms-azuretools.vscode-docker


